name: Build macOS App

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-macos:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install system dependencies
      run: |
        brew install imagemagick create-dmg
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r build_requirements.txt
        pip install -r requirements.txt
    
    - name: Create app icon
      run: |
        cd build_resources
        python create_app_icon.py
        cd ..
    
    - name: Build macOS app
      run: |
        python build_mac_app.py
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: macos-build
        path: |
          *.dmg
          *.zip
    
    - name: Create Release and Upload Assets
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      with:
        name: Release ${{ github.ref_name }}
        body: |
          ## FluoroSpot Analysis Tool ${{ github.ref_name }}
          
          ### Downloads
          - **Intel Mac**: Download the `FluoroSpot_Analysis_Intel.dmg` file
          - **Apple Silicon Mac**: Download the `FluoroSpot_Analysis_Apple-Silicon.dmg` file
          
          ### Installation
          1. Download the appropriate DMG file for your Mac
          2. Double-click to mount the DMG
          3. Drag the application to your Applications folder
          4. Run the application from Applications
          
          ### Changes
          See the commit history for details on changes in this release.
        files: |
          *.dmg
          *.zip
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}