name: Build macOS App

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-macos:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install system dependencies
      run: |
        brew install imagemagick create-dmg
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r build_requirements.txt
        pip install -r requirements.txt
    
    - name: Create app icon
      run: |
        cd build_resources
        python create_app_icon.py
        cd ..
    
    - name: Build macOS app
      run: |
        python build_mac_app.py
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: macos-build
        path: |
          FluoroSpot_Analysis.dmg
          FluoroSpot_Analysis_Mac.zip